version: "{build}"

platform:
  - x64

install:
  - appveyor DownloadFile http://curl.haxx.se/ca/cacert.pem -FileName C:\cacert.pem

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%\consul
  - download.bat
  - choco pack consul.nuspec

test_script:
  - cinst consul -fdvy -source "'%cd%;https://chocolatey.org/api/v2/'"
  - cuninst -fdvy consul

artifacts:
  - path: '**\*.nupkg'

deploy: off
