version: 0.7.4.1.{build}

environment:
  TOKEN:
    secure: 3sxpbbTFvPJlNQ7fwBDGM6EkuisTVEnALEK9Krtx5zAOvXdaIo+jCql4ms7cyFyj

platform:
  - x64

install:
  - appveyor DownloadFile http://curl.haxx.se/ca/cacert.pem -FileName C:\cacert.pem

build_script:
  - ps: >-
      $env:CONSUL_VERSION = $env:APPVEYOR_BUILD_VERSION -replace('\.[^.\\/]+$');
      cmd /c download.bat;
      choco pack consul.nuspec

test_script:
  - ps: cinst consul -fdvy -source "$pwd;http://chocolatey.org/api/v2/"
  - ps: cuninst -fdvy consul

deploy_script:
  - ps: >-
      Write-Host $env:APPVEYOR_REPO_TAG;
      if($env:APPVEYOR_REPO_BRANCH -eq 'master' -And $env:APPVEYOR_REPO_TAG -eq 'true') {
        $version = $env:APPVEYOR_BUILD_VERSION -replace('\.[^.\\/]+$');
        choco apiKey -k $env:TOKEN -source https://chocolatey.org/;
        choco push consul.$version.nupkg
      }

artifacts:
  - path: '**\*.nupkg'
